### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by doughsay** [rap1ds/ruby-possibly#17]
I really like what you've got here, but noticed you have many open pull requests from over a year ago with some good looking functionality in them.  Are you planning on merging those ever?  Is a release 0.3.0 possible?

**Comment by rap1ds** [comment]
@doughsay Definitely not abandoned! :)

I added those Pull Requests there long ago, and back then I wasn't sure if those were so critical that they should be merged. I want to keep the library small and not to merge any functionality, unless there's a clear need for that. We are using the library actively at [Sharetribe](https://www.github.com/sharetribe/sharetribe) and I haven't felt urgent need for any of those functionalities that are in the Pull Requests, so that's why I haven't merged them.

My current thinking is that the releae 0.3.0 will not happen, at least in a form of the current open Pull Request #11. I feel that #14 could be merged and maybe #7, but other than that I'm not so sure if I want to merge the others.

Is there some PR open at the moment that you'd specifically want to get merged?

**Comment by doughsay** [comment]
Good to hear!

No, there wasn't anything in particular I was looking to see merged.  I'm very interested in using this gem, and just wanted to make sure I wasn't backing something that nobody cared about anymore.

Thanks!
